name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Copy example env
        shell: bash
        run: cp .env.example .env

      - name: Run linter
        run: SKIP_ENV_VALIDATION=1 pnpm lint